### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

###

### Ver clases
GET http://localhost:8000/api/clases
Authorization: Bearer 1|V8kCYJusFy7pUy2TgmXg1AUIQrk9mL0j5uhp2HEo124247e2

###

### Crear clase
POST http://localhost:8000/api/clases
Authorization: Bearer 1|V8kCYJusFy7pUy2TgmXg1AUIQrk9mL0j5uhp2HEo124247e2
Content-Type: application/json

{
    "nombre": "Zumba",
    "descripcion": "Clase de baile fitness",
    "diaSemana": "Lunes",
    "horario": "08:00:00",
    "capacidad": 20
}

###

### Ver usuarios
GET http://localhost:8000/api/usuarios
Authorization: Bearer 1|V8kCYJusFy7pUy2TgmXg1AUIQrk9mL0j5uhp2HEo124247e2

###

### Ver reservas
GET http://localhost:8000/api/reservas
Authorization: Bearer 1|V8kCYJusFy7pUy2TgmXg1AUIQrk9mL0j5uhp2HEo124247e2